name: part_wit
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  dio: ^4.0.4
  get: ^4.3.8
  get_storage: ^2.0.3
  http: ^0.13.4
  image_picker: ^0.8.4+4
  pinput: ^1.2.2
  intl: ^0.17.0
  fluttertoast: ^8.0.8
  connectivity: ^3.0.6
  shared_preferences: ^2.0.9
  provider:
  flutter_lints: ^1.0.0
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^3.5.6+3
  location: ^4.2.0
  permission_handler: ^8.2.0
  flutter_rating_bar: ^4.0.0
#  contained_tab_bar_view_with_custom_page_navigator: ^0.1.3
  flutter_share: ^2.0.0
  stripe_payment:
  carousel_slider: ^4.0.0
  html: ^0.15.0
#  multi_image_picker2: ^5.0.2
  video_player: ^2.2.18
  flutter_socket_io: ^0.6.0
  font_awesome_flutter: ^8.5.0
  lottie: ^0.2.1
  http_interceptor: ^1.0.1
  flutter_html: ^2.2.1
  percent_indicator: ^4.0.0
  readmore: ^2.1.0
  #location_permissions: ^4.0.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/locales/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages



  fonts:
    - family: FuturaPT
      fonts:
        - asset:  assets/fonts/futura-pt-book.otf
          weight:  100
        - asset:  assets/fonts/futura-pt-demi.otf
          weight:  200
        - asset:  assets/fonts/futura-pt-heavy.otf
          weight:  300
        - asset:  assets/fonts/futura-pt-light.otf
          weight:  400
        - asset:  assets/fonts/futura-pt-medium.otf
          weight:  500
        - asset:  assets/fonts/futura-pt-bold.otf
          weight:  600



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
